package com.company.iceshield.paneles;

import com.company.iceshield.IceShield;
import com.company.iceshield.files.ConfigFile;
import com.company.iceshield.jLogin;
import java.awt.BorderLayout;
import java.awt.Color;


public class JconfigBD extends javax.swing.JPanel {

    /**
     * Creates new form JconfigBD
     */
    ConfigFile cf = new ConfigFile();

    public JconfigBD() {
        initComponents();
        setSize(1310, 596);
        txt_ip_input.setText(cf.getmsqlHost());
        port_input.setText(cf.getmsqlPort());
        namedb_input.setText(cf.getmsqlNameDB());
        user_input1.setText(cf.getmsqlUser());
        password_input.setText(cf.getmsqlPass());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_jconfigbd = new javax.swing.JLabel();
        txt_ip = new javax.swing.JLabel();
        txt_ip_input = new com.company.iceshield.others.MyTextField();
        password_txt = new javax.swing.JLabel();
        password_input = new com.company.iceshield.others.MyTextField();
        port_txt1 = new javax.swing.JLabel();
        port_input = new com.company.iceshield.others.MyTextField();
        user_txt1 = new javax.swing.JLabel();
        user_input1 = new com.company.iceshield.others.MyTextField();
        namedb_input = new com.company.iceshield.others.MyTextField();
        password_txt1 = new javax.swing.JLabel();
        btn_guardar = new com.company.iceshield.others.JPanelRound();
        jLabel1 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 171, 33));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_jconfigbd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_jconfigbd.setForeground(new java.awt.Color(255, 255, 255));
        txt_jconfigbd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_jconfigbd.setText("Configuración BaseDatos");
        add(txt_jconfigbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        txt_ip.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_ip.setText("Host:");
        add(txt_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txt_ip_input.setText("localhost");
        txt_ip_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ip_inputActionPerformed(evt);
            }
        });
        add(txt_ip_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 360, 40));

        password_txt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password_txt.setText("Password:");
        add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        password_input.setText("Password");
        add(password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 360, 40));

        port_txt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        port_txt1.setText("Port:");
        add(port_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 165, -1, -1));

        port_input.setText("3306");
        add(port_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 360, 40));

        user_txt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user_txt1.setText("User:");
        add(user_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        user_input1.setText("root");
        add(user_input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 360, 40));

        namedb_input.setText("HeladeriaDB");
        add(namedb_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 360, 40));

        password_txt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password_txt1.setText("NameBD:");
        add(password_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        btn_guardar.setBackground(new java.awt.Color(237, 226, 79));
        btn_guardar.setRoundBottomLeft(9);
        btn_guardar.setRoundBottomRight(9);
        btn_guardar.setRoundTopLeft(9);
        btn_guardar.setRoundTopRight(9);
        btn_guardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guardar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        btn_guardar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 240, 50));

        txt_cod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_cod.setForeground(new java.awt.Color(102, 255, 102));
        txt_cod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(txt_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 470, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ip_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ip_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ip_inputActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        cf.setAppHost(txt_ip_input.getText());
        cf.setAppPort(port_input.getText());
        cf.setAppnameDB(namedb_input.getText());
        cf.setAppUser(user_input1.getText());
        cf.setAppPass(password_input.getText());
        txt_cod.setText("Se guardo Satisfactoriamente");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        btn_guardar.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        btn_guardar.setBackground(new Color(249,238,96));
    }//GEN-LAST:event_jLabel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.company.iceshield.others.JPanelRound btn_guardar;
    private javax.swing.JLabel jLabel1;
    private com.company.iceshield.others.MyTextField namedb_input;
    private com.company.iceshield.others.MyTextField password_input;
    private javax.swing.JLabel password_txt;
    private javax.swing.JLabel password_txt1;
    private com.company.iceshield.others.MyTextField port_input;
    private javax.swing.JLabel port_txt1;
    private javax.swing.JLabel txt_cod;
    private javax.swing.JLabel txt_ip;
    private com.company.iceshield.others.MyTextField txt_ip_input;
    private javax.swing.JLabel txt_jconfigbd;
    private com.company.iceshield.others.MyTextField user_input1;
    private javax.swing.JLabel user_txt1;
    // End of variables declaration//GEN-END:variables
}
