/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.iceshield.paneles;

/**
 *
 * @author Luidev02
 */
public class JconfigBD extends javax.swing.JPanel {

    /**
     * Creates new form JconfigBD
     */
    public JconfigBD() {
        initComponents();
        setSize(1310, 596);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_jconfigbd = new javax.swing.JLabel();
        txt_ip = new javax.swing.JLabel();
        txt_ip_input = new com.company.iceshield.others.MyTextField();
        user_txt = new javax.swing.JLabel();
        user_input = new com.company.iceshield.others.MyTextField();
        port_txt1 = new javax.swing.JLabel();
        port_input = new com.company.iceshield.others.MyTextField();

        setBackground(new java.awt.Color(254, 171, 33));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_jconfigbd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_jconfigbd.setForeground(new java.awt.Color(255, 255, 255));
        txt_jconfigbd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_jconfigbd.setText("Configuración BaseDatos");
        add(txt_jconfigbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, -1));

        txt_ip.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_ip.setText("Host:");
        add(txt_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txt_ip_input.setText("localhost");
        txt_ip_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ip_inputActionPerformed(evt);
            }
        });
        add(txt_ip_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 360, 40));

        user_txt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        user_txt.setText("User:");
        add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        user_input.setText("root");
        add(user_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 360, 40));

        port_txt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        port_txt1.setText("Port:");
        add(port_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 165, -1, -1));

        port_input.setText("3306");
        add(port_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 360, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ip_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ip_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ip_inputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.company.iceshield.others.MyTextField port_input;
    private javax.swing.JLabel port_txt1;
    private javax.swing.JLabel txt_ip;
    private com.company.iceshield.others.MyTextField txt_ip_input;
    private javax.swing.JLabel txt_jconfigbd;
    private com.company.iceshield.others.MyTextField user_input;
    private javax.swing.JLabel user_txt;
    // End of variables declaration//GEN-END:variables
}
