
package com.company.iceshield.paneles;

import java.awt.Color;


public class JGestor extends javax.swing.JPanel {


    public JGestor() {
        initComponents();
        setSize(1310, 596);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_icons = new com.company.iceshield.others.JPanelRound();
        bg_icons_d = new com.company.iceshield.others.JPanelRound();
        btn_1 = new com.company.iceshield.others.JPanelRound();
        btn_1_click = new javax.swing.JLabel();
        btn_2 = new com.company.iceshield.others.JPanelRound();
        btn_2_click = new javax.swing.JLabel();
        btn_3 = new com.company.iceshield.others.JPanelRound();
        btn_3_click = new javax.swing.JLabel();
        btn_4 = new com.company.iceshield.others.JPanelRound();
        btn_4_click = new javax.swing.JLabel();
        btn_5 = new com.company.iceshield.others.JPanelRound();
        btn_5_click = new javax.swing.JLabel();
        btn_6 = new com.company.iceshield.others.JPanelRound();
        btn_6_click = new javax.swing.JLabel();
        btn_7 = new com.company.iceshield.others.JPanelRound();
        btn_7_click = new javax.swing.JLabel();
        btn_8 = new com.company.iceshield.others.JPanelRound();
        btn_8_click = new javax.swing.JLabel();
        btn_9 = new com.company.iceshield.others.JPanelRound();
        btn_9_click = new javax.swing.JLabel();
        table_table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_total = new javax.swing.JLabel();
        txt_money = new com.company.iceshield.others.JPanelRound();
        txt_money_label = new javax.swing.JLabel();
        btn_limpiar = new com.company.iceshield.others.JPanelRound();
        btn_txt_limpiar = new javax.swing.JLabel();
        btn_recibir = new com.company.iceshield.others.JPanelRound();
        btn_txt_recibir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 171, 33));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_icons.setBackground(new java.awt.Color(243, 232, 81));
        bg_icons.setPreferredSize(new java.awt.Dimension(696, 539));
        bg_icons.setRoundBottomLeft(12);
        bg_icons.setRoundBottomRight(12);
        bg_icons.setRoundTopLeft(12);
        bg_icons.setRoundTopRight(12);
        bg_icons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_icons_d.setBackground(new java.awt.Color(254, 171, 33));
        bg_icons_d.setRoundBottomLeft(12);
        bg_icons_d.setRoundBottomRight(12);
        bg_icons_d.setRoundTopLeft(12);
        bg_icons_d.setRoundTopRight(12);

        btn_1.setBackground(new java.awt.Color(243, 232, 81));
        btn_1.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_1.setRoundBottomLeft(8);
        btn_1.setRoundBottomRight(8);
        btn_1.setRoundTopLeft(8);
        btn_1.setRoundTopRight(8);

        btn_1_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_1_click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_1_clickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_1_clickMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_1_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_1_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_2.setBackground(new java.awt.Color(243, 232, 81));
        btn_2.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_2.setRoundBottomLeft(8);
        btn_2.setRoundBottomRight(8);
        btn_2.setRoundTopLeft(8);
        btn_2.setRoundTopRight(8);

        btn_2_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_2_click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_2_clickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_2_clickMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_2_click, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_2_click, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_3.setBackground(new java.awt.Color(243, 232, 81));
        btn_3.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_3.setRoundBottomLeft(8);
        btn_3.setRoundBottomRight(8);
        btn_3.setRoundTopLeft(8);
        btn_3.setRoundTopRight(8);

        btn_3_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_3_click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_3_clickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_3_clickMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_3_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_3_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_4.setBackground(new java.awt.Color(243, 232, 81));
        btn_4.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_4.setRoundBottomLeft(8);
        btn_4.setRoundBottomRight(8);
        btn_4.setRoundTopLeft(8);
        btn_4.setRoundTopRight(8);

        btn_4_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_4_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_4Layout.setVerticalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_4_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_5.setBackground(new java.awt.Color(243, 232, 81));
        btn_5.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_5.setRoundBottomLeft(8);
        btn_5.setRoundBottomRight(8);
        btn_5.setRoundTopLeft(8);
        btn_5.setRoundTopRight(8);

        btn_5_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_5Layout = new javax.swing.GroupLayout(btn_5);
        btn_5.setLayout(btn_5Layout);
        btn_5Layout.setHorizontalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_5_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_5Layout.setVerticalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_5_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_6.setBackground(new java.awt.Color(243, 232, 81));
        btn_6.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_6.setRoundBottomLeft(8);
        btn_6.setRoundBottomRight(8);
        btn_6.setRoundTopLeft(8);
        btn_6.setRoundTopRight(8);

        btn_6_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_6Layout = new javax.swing.GroupLayout(btn_6);
        btn_6.setLayout(btn_6Layout);
        btn_6Layout.setHorizontalGroup(
            btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_6_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_6Layout.setVerticalGroup(
            btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_6_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_7.setBackground(new java.awt.Color(243, 232, 81));
        btn_7.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_7.setRoundBottomLeft(8);
        btn_7.setRoundBottomRight(8);
        btn_7.setRoundTopLeft(8);
        btn_7.setRoundTopRight(8);

        btn_7_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_7Layout = new javax.swing.GroupLayout(btn_7);
        btn_7.setLayout(btn_7Layout);
        btn_7Layout.setHorizontalGroup(
            btn_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_7_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_7Layout.setVerticalGroup(
            btn_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_7_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_8.setBackground(new java.awt.Color(243, 232, 81));
        btn_8.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_8.setRoundBottomLeft(8);
        btn_8.setRoundBottomRight(8);
        btn_8.setRoundTopLeft(8);
        btn_8.setRoundTopRight(8);

        btn_8_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_8Layout = new javax.swing.GroupLayout(btn_8);
        btn_8.setLayout(btn_8Layout);
        btn_8Layout.setHorizontalGroup(
            btn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_8_click, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_8Layout.setVerticalGroup(
            btn_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_8_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        btn_9.setBackground(new java.awt.Color(243, 232, 81));
        btn_9.setPreferredSize(new java.awt.Dimension(201, 145));
        btn_9.setRoundBottomLeft(8);
        btn_9.setRoundBottomRight(8);
        btn_9.setRoundTopLeft(8);
        btn_9.setRoundTopRight(8);

        btn_9_click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_9Layout = new javax.swing.GroupLayout(btn_9);
        btn_9.setLayout(btn_9Layout);
        btn_9Layout.setHorizontalGroup(
            btn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_9_click, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        btn_9Layout.setVerticalGroup(
            btn_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_9_click, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_icons_dLayout = new javax.swing.GroupLayout(bg_icons_d);
        bg_icons_d.setLayout(bg_icons_dLayout);
        bg_icons_dLayout.setHorizontalGroup(
            bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_icons_dLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_icons_dLayout.createSequentialGroup()
                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_icons_dLayout.createSequentialGroup()
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_icons_dLayout.createSequentialGroup()
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        bg_icons_dLayout.setVerticalGroup(
            bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_icons_dLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_icons_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        bg_icons.add(bg_icons_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 520));

        add(bg_icons, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 24, -1, -1));

        table_table.setPreferredSize(new java.awt.Dimension(535, 289));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Unidad U.", "Precio", "Precio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(535, 289));
        jTable1.getTableHeader().setReorderingAllowed(false);
        table_table.setViewportView(jTable1);

        add(table_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 540, 320));

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_total.setText("Total:");
        add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 390, -1, -1));

        txt_money.setRoundBottomLeft(6);
        txt_money.setRoundBottomRight(6);
        txt_money.setRoundTopLeft(6);
        txt_money.setRoundTopRight(6);

        txt_money_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_money_label.setText("0$");

        javax.swing.GroupLayout txt_moneyLayout = new javax.swing.GroupLayout(txt_money);
        txt_money.setLayout(txt_moneyLayout);
        txt_moneyLayout.setHorizontalGroup(
            txt_moneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_moneyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_money_label, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
        );
        txt_moneyLayout.setVerticalGroup(
            txt_moneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_money_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(txt_money, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 380, 170, 40));

        btn_limpiar.setBackground(new java.awt.Color(243, 110, 81));
        btn_limpiar.setRoundBottomLeft(9);
        btn_limpiar.setRoundBottomRight(9);
        btn_limpiar.setRoundTopLeft(9);
        btn_limpiar.setRoundTopRight(9);

        btn_txt_limpiar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_txt_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_txt_limpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_txt_limpiar.setText("Limpiar");

        javax.swing.GroupLayout btn_limpiarLayout = new javax.swing.GroupLayout(btn_limpiar);
        btn_limpiar.setLayout(btn_limpiarLayout);
        btn_limpiarLayout.setHorizontalGroup(
            btn_limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_txt_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btn_limpiarLayout.setVerticalGroup(
            btn_limpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_txt_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 190, 50));

        btn_recibir.setBackground(new java.awt.Color(237, 226, 79));
        btn_recibir.setRoundBottomLeft(9);
        btn_recibir.setRoundBottomRight(9);
        btn_recibir.setRoundTopLeft(9);
        btn_recibir.setRoundTopRight(9);

        btn_txt_recibir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_txt_recibir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_txt_recibir.setText("Recibir Dinero");

        javax.swing.GroupLayout btn_recibirLayout = new javax.swing.GroupLayout(btn_recibir);
        btn_recibir.setLayout(btn_recibirLayout);
        btn_recibirLayout.setHorizontalGroup(
            btn_recibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_txt_recibir, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btn_recibirLayout.setVerticalGroup(
            btn_recibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_txt_recibir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(btn_recibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 220, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1_clickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_clickMouseEntered
        btn_1.setBackground(new Color(245,232,57));
    }//GEN-LAST:event_btn_1_clickMouseEntered

    private void btn_1_clickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_clickMouseExited
        btn_1.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_btn_1_clickMouseExited

    private void btn_2_clickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2_clickMouseEntered
        btn_2.setBackground(new Color(245,232,57));
    }//GEN-LAST:event_btn_2_clickMouseEntered

    private void btn_2_clickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2_clickMouseExited
        btn_2.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_btn_2_clickMouseExited

    private void btn_3_clickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3_clickMouseEntered
        btn_3.setBackground(new Color(245,232,57));
    }//GEN-LAST:event_btn_3_clickMouseEntered

    private void btn_3_clickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3_clickMouseExited
        btn_3.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_btn_3_clickMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.company.iceshield.others.JPanelRound bg_icons;
    private com.company.iceshield.others.JPanelRound bg_icons_d;
    private com.company.iceshield.others.JPanelRound btn_1;
    private javax.swing.JLabel btn_1_click;
    private com.company.iceshield.others.JPanelRound btn_2;
    private javax.swing.JLabel btn_2_click;
    private com.company.iceshield.others.JPanelRound btn_3;
    private javax.swing.JLabel btn_3_click;
    private com.company.iceshield.others.JPanelRound btn_4;
    private javax.swing.JLabel btn_4_click;
    private com.company.iceshield.others.JPanelRound btn_5;
    private javax.swing.JLabel btn_5_click;
    private com.company.iceshield.others.JPanelRound btn_6;
    private javax.swing.JLabel btn_6_click;
    private com.company.iceshield.others.JPanelRound btn_7;
    private javax.swing.JLabel btn_7_click;
    private com.company.iceshield.others.JPanelRound btn_8;
    private javax.swing.JLabel btn_8_click;
    private com.company.iceshield.others.JPanelRound btn_9;
    private javax.swing.JLabel btn_9_click;
    private com.company.iceshield.others.JPanelRound btn_limpiar;
    private com.company.iceshield.others.JPanelRound btn_recibir;
    private javax.swing.JLabel btn_txt_limpiar;
    private javax.swing.JLabel btn_txt_recibir;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane table_table;
    private com.company.iceshield.others.JPanelRound txt_money;
    private javax.swing.JLabel txt_money_label;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
