
package com.company.iceshield.paneles;

import com.company.iceshield.files.ConfigFile;
import java.awt.BorderLayout;
import java.awt.Color;


public class JPrincipal extends javax.swing.JPanel {

    JConfig jc = new JConfig();
    JGestor jg = new JGestor();
    JReport jr = new JReport();
    public JPrincipal() {
        initComponents();
        setSize(1310, 596);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_fondo = new javax.swing.JLabel();
        btn_1 = new com.company.iceshield.others.JPanelRound();
        clic_btn1 = new javax.swing.JLabel();
        btn1_img = new javax.swing.JLabel();
        btn1_txt = new javax.swing.JLabel();
        btn_2 = new com.company.iceshield.others.JPanelRound();
        btn2_clic = new javax.swing.JLabel();
        btn2_img = new javax.swing.JLabel();
        btn2_txt = new javax.swing.JLabel();
        btn_3 = new com.company.iceshield.others.JPanelRound();
        btn3_clic = new javax.swing.JLabel();
        btn3_icon = new javax.swing.JLabel();
        btn3_txt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 171, 33));

        img_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_menu.png"))); // NOI18N

        btn_1.setBackground(new java.awt.Color(249, 238, 96));
        btn_1.setRoundBottomLeft(14);
        btn_1.setRoundBottomRight(14);
        btn_1.setRoundTopLeft(14);
        btn_1.setRoundTopRight(14);
        btn_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clic_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clic_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clic_btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clic_btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clic_btn1MouseExited(evt);
            }
        });
        btn_1.add(clic_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 190));

        btn1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_icon.png"))); // NOI18N
        btn_1.add(btn1_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 32, -1, -1));

        btn1_txt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn1_txt.setText("Gestor de ventas");
        btn_1.add(btn1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 252, -1));

        btn_2.setBackground(new java.awt.Color(249, 238, 96));
        btn_2.setRoundBottomLeft(14);
        btn_2.setRoundBottomRight(14);
        btn_2.setRoundTopLeft(14);
        btn_2.setRoundTopRight(14);
        btn_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn2_clic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2_clic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2_clicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2_clicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2_clicMouseExited(evt);
            }
        });
        btn_2.add(btn2_clic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 190));

        btn2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config_icon.png"))); // NOI18N
        btn_2.add(btn2_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 43, -1, -1));

        btn2_txt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn2_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn2_txt.setText("Configuración");
        btn_2.add(btn2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 252, -1));

        btn_3.setBackground(new java.awt.Color(249, 238, 96));
        btn_3.setRoundBottomLeft(14);
        btn_3.setRoundBottomRight(14);
        btn_3.setRoundTopLeft(14);
        btn_3.setRoundTopRight(14);
        btn_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3_clic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_clic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3_clicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3_clicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3_clicMouseExited(evt);
            }
        });
        btn_3.add(btn3_clic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 190));

        btn3_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copy_icon.png"))); // NOI18N
        btn_3.add(btn3_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 38, -1, -1));

        btn3_txt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn3_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn3_txt.setText("Copia Y Reportes");
        btn_3.add(btn3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 106, 252, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img_fondo)
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(img_fondo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clic_btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clic_btn1MouseEntered
        btn_1.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_clic_btn1MouseEntered

    private void clic_btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clic_btn1MouseExited
        btn_1.setBackground(new Color(249,238,96));
    }//GEN-LAST:event_clic_btn1MouseExited

    private void btn2_clicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2_clicMouseEntered
        btn_2.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_btn2_clicMouseEntered

    private void btn2_clicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2_clicMouseExited
        btn_2.setBackground(new Color(249,238,96));
    }//GEN-LAST:event_btn2_clicMouseExited

    private void btn3_clicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3_clicMouseEntered
        btn_3.setBackground(new Color(243,232,81));
    }//GEN-LAST:event_btn3_clicMouseEntered

    private void btn3_clicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3_clicMouseExited
        btn_3.setBackground(new Color(249,238,96));
    }//GEN-LAST:event_btn3_clicMouseExited

    private void btn2_clicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2_clicMouseClicked
        ConfigFile cf = new ConfigFile();
        
        if(cf.getapprol().equals("administrador")){
            jMain.fondo_mv.removeAll();
            jMain.fondo_mv.add(jc,BorderLayout.CENTER);
            jMain.fondo_mv.revalidate();
            jMain.fondo_mv.repaint();
        }else{
            btn_2.setBackground(Color.red);
        }

    }//GEN-LAST:event_btn2_clicMouseClicked

    private void clic_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clic_btn1MouseClicked
        jMain.fondo_mv.removeAll();
        jMain.fondo_mv.add(jg,BorderLayout.CENTER);
        jMain.fondo_mv.revalidate();
        jMain.fondo_mv.repaint();
    }//GEN-LAST:event_clic_btn1MouseClicked
    
    private void btn3_clicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3_clicMouseClicked
        
        ConfigFile cf = new ConfigFile();
        
        if(cf.getapprol().equals("administrador")){
            jMain.fondo_mv.removeAll();
            jMain.fondo_mv.add(jr,BorderLayout.CENTER);
            jMain.fondo_mv.revalidate();
            jMain.fondo_mv.repaint();
        }else{
            btn_3.setBackground(Color.red);
        }
        


    }//GEN-LAST:event_btn3_clicMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn1_img;
    private javax.swing.JLabel btn1_txt;
    private javax.swing.JLabel btn2_clic;
    private javax.swing.JLabel btn2_img;
    private javax.swing.JLabel btn2_txt;
    private javax.swing.JLabel btn3_clic;
    private javax.swing.JLabel btn3_icon;
    private javax.swing.JLabel btn3_txt;
    private com.company.iceshield.others.JPanelRound btn_1;
    private com.company.iceshield.others.JPanelRound btn_2;
    private com.company.iceshield.others.JPanelRound btn_3;
    private javax.swing.JLabel clic_btn1;
    private javax.swing.JLabel img_fondo;
    // End of variables declaration//GEN-END:variables
}
