
package com.company.iceshield;

import java.awt.Color;

public class jLogin extends javax.swing.JFrame {

    /**
     * Creates new form jLogin
     */
    int xMouse,yMouse;
    public jLogin() {
        initComponents();
        setSize(891, 501);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btn_mini = new javax.swing.JPanel();
        label_mini = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        label_exit = new javax.swing.JLabel();
        icon_logo = new javax.swing.JLabel();
        Bg_img = new javax.swing.JLabel();
        moviment_top = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mini.setBackground(new java.awt.Color(254, 171, 33));
        btn_mini.setPreferredSize(new java.awt.Dimension(30, 30));

        label_mini.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mini.setText("-");
        label_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_miniMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_miniLayout = new javax.swing.GroupLayout(btn_mini);
        btn_mini.setLayout(btn_miniLayout);
        btn_miniLayout.setHorizontalGroup(
            btn_miniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_mini, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btn_miniLayout.setVerticalGroup(
            btn_miniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_mini, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(btn_mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        btn_exit.setBackground(new java.awt.Color(254, 171, 33));

        label_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        icon_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_icesheald.png"))); // NOI18N
        icon_logo.setToolTipText("");
        bg.add(icon_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        Bg_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bg_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg-Login.png"))); // NOI18N
        bg.add(Bg_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        moviment_top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moviment_topMouseDragged(evt);
            }
        });
        moviment_top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moviment_topMousePressed(evt);
            }
        });

        javax.swing.GroupLayout moviment_topLayout = new javax.swing.GroupLayout(moviment_top);
        moviment_top.setLayout(moviment_topLayout);
        moviment_topLayout.setHorizontalGroup(
            moviment_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        moviment_topLayout.setVerticalGroup(
            moviment_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(moviment_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moviment_topMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviment_topMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moviment_topMousePressed

    private void moviment_topMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviment_topMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
                
    }//GEN-LAST:event_moviment_topMouseDragged

    private void label_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_miniMouseExited
        btn_mini.setBackground(new Color(254,171,33));
    }//GEN-LAST:event_label_miniMouseExited

    private void label_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_miniMouseEntered
        btn_mini.setBackground(new Color(210,141,25));
    }//GEN-LAST:event_label_miniMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        btn_exit.setBackground(new Color(254,171,33));
    }//GEN-LAST:event_label_exitMouseExited

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        btn_exit.setBackground(Color.red);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_miniMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_label_miniMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg_img;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_mini;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel label_exit;
    private javax.swing.JLabel label_mini;
    private javax.swing.JPanel moviment_top;
    // End of variables declaration//GEN-END:variables
}
